apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuananh-dep
  namespace: deploy-argocd-test
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: test-gitops
          image: tuannanhh/test-gitops:52
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tuananh-svc
  namespace: deploy-argocd-test
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#       nodePort: 30132
